global using BusinessLogic;
global using Microsoft.AspNetCore.Mvc;
global using Model.Setup.Blog;
global using PresentationLayer.Resources;
global using Newtonsoft.Json;
global using PresentationLayer.Services;
global using DataAccess.Services;
global using DbService;
global using Microsoft.EntityFrameworkCore;
